package io.ruin.model.entity.attributes;

/**
 * @author Mrbennjerry - https://github.com/Mrbennjerry
 * Created on 8/16/2021
 */
public enum AttributeKey {
    GRAIN_IN_HOPPER,
    URI_CLUE,
    LAST_EMOTE,
    URI_SPAWNED,
    ESSENCE_TELEPORT,
    HOT_AND_COLD,
    KILLED_WIZARD,
    SPAWNED_WIZARD,
    FALO_SONG,
    SUPERIOR_SPAWNED,
    SHOOTING_STARS_FOUND,
    BOOK,
    SLAUGHTER_CHARGES,
    EXPEDITIOUS_CHARGES,
    CAMULET_CHARGES,
    DODGY_NECKLACE_CHARGES,
    XP_COUNTER_START,
    XP_COUNTER_GOAL,
    EFARITAYS_CHARGES,
    TASK_ONLY,
    COSTUME_STORAGE,
    COSTUME_BUILDABLE,
    DROP_VIEWER_RESULTS,
    LIEVE_KRAKEN_TENTACLES,
    CRAB_TRANSFORM,
    DIALOGUE_ACTION_ARGUMENTS,
    IKOD_PROTECT_ITEM,
    IKOD_SKULL,
    IKOD_PK,
    IKOD_WILDY
}
