package io.ruin.model.entity.player;

public enum PlayerCounter {

    /**
     * Blast furnace
     */
    SMITHED_BARS,

    /**
     * Runecrafting
     */
    CRAFTED_AIR,
    CRAFTED_MIND,
    CRAFTED_WATER,
    CRAFTED_EARTH,
    CRAFTED_FIRE,
    CRAFTED_BODY,
    CRAFTED_COSMIC,
    CRAFTED_LAW,
    CRAFTED_NATURE,
    CRAFTED_CHAOS,
    CRAFTED_DEATH,
    CRAFTED_ASTRAL,
    CRAFTED_BLOOD,
    CRAFTED_SOUL,
    CRAFTED_WRATH,

    /**
     * Agility
     */
    GNOME_STRONGHOLD_COURSE,
    BARBARIAN_COURSE,
    WILDERNESS_COURSE,
    DRAYNOR_ROOFTOP,
    ALKHARID_ROOFTOP,
    VARROCK_ROOFTOP,
    CANIFIS_ROOFTOP,
    FALADOR_ROOFTOP,
    SEERS_ROOFTOP,
    RELLEKKA_ROOFTOP,
    ARDOUGNE_ROOFTOP,
    POLLNIVNEACH_ROOFTOP,
    PRIFDDINAS_COURSE,
    AGILITY_PYRAMID,

    /**
     * Woodcutting
     */
    CHOPPED_REGULAR,
    CHOPPED_SAPLING,
    CHOPPED_ACHEY,
    CHOPPED_OAK,
    CHOPPED_WILLOW,
    CHOPPED_TEAK,
    CHOPPED_JUNIPER,
    CHOPPED_MAPLE,
    CHOPPED_YEW,
    CHOPPED_MAGIC,
    CHOPPED_REDWOOD,
    CHOPPED_MAHOGANY,
    CHOPPED_CORRUPT,
    CHOPPED_ENTS,
    OPENED_BIRDS_NESTS,
    ACQUIRED_BIRDS_NESTS,

    /**
     * Mining
     */
    MINED_CLAY,
    MINED_COPPER,
    MINED_TIN,
    MINED_IRON,
    MINED_SILVER,
    MINED_COAL,
    MINED_GOLD,
    MINED_MITHRIL,
    MINED_LOVAKITE,
    MINED_ADAMANT,
    MINED_RUNITE,
    MINED_AMETHYST,
    MINED_RUNE_ESSENCE,
    MINED_PURE_ESSENCE,
    MINED_DARK_ESSENCE,
    MINED_GEODE,
    MINED_SANDSTONE,
    MINED_GRANITE,
    MINED_GEM_ROCK,
    MINE_SALT,
    MINED_CORRUPT,
    MINED_STARDUST,
    MINED_LIMESTONE,

    /**
     * Smithing
     */
    SMELTED_BRONZE_BARS,
    SMELTED_BLURITE_BARS,
    SMELTED_IRON_BARS,
    SMELTED_SILVER_BARS,
    SMELTED_STEEL_BARS,
    SMELTED_GOLD_BARS,
    SMELTED_MITHRIL_BARS,
    SMELTED_ADAMANT_BARS,
    SMELTED_RUNITE_BARS,
    SMELTED_CORRUPT_BARS,

    /**
     * Thieving
     */
    VEGETABLE_STALL_THIEVES,
    BAKER_STALL_THIEVES,
    CRAFTING_STALL_THIEVES,
    MONKEY_FOOD_STALL_THIEVES,
    MONKEY_GENERAL_STALL_THIEVES,
    TEA_STALL_THIEVES,
    SILK_STALL_THIEVES,
    WINE_STALL_THIEVES,
    FRUIT_STALL_THIEVES,
    SEED_STALL_THIEVES,
    FUR_STALL_THIEVES,
    FISH_STALL_THIEVES,
    CROSSBOW_STALL_THIEVES,
    SILVER_STALL_THIEVES,
    SPICE_STALL_THIEVES,
    MAGIC_STALL_THIEVES,
    SCIMITAR_STALL_THIEVES,
    GEM_STALL_THIEVES,
    MOR_GEM_STALL_THIEVES,
    ORE_STALL_THIEVES,
    PICKPOCKETED_MAN,
    PICKPOCKETED_FARMER,
    PICKPOCKETED_WARRIOR,
    PICKPOCKETED_HAM_MEMBER,
    PICKPOCKETED_ROGUE,
    PICKPOCKETED_CAVE_GOBLIN,
    PICKPOCKETED_MASTER_FARMER,
    PICKPOCKETED_GUARD,
    PICKPOCKETED_BANDIT,
    PICKPOCKETED_KNIGHT,
    PICKPOCKETED_WATCHMAN,
    PICKPOCKETED_PALADIN,
    PICKPOCKETED_GNOME,
    PICKPOCKETED_HERO,
    PICKPOCKETED_VYRE,
    PICKPOCKETED_ELF,
    PICKPOCKETED_TZHAAR_HUR,
    WALL_SAFES_CRACKED,
    ROGUES_CASTLE_CHESTS,
    PICKED_LOCKS,

    /**
     * Firemaking
     */
    NORMAL_LOGS_BURNT,
    ACHEY_LOGS_BURNT,
    OAK_LOGS_BURNT,
    WILLOW_LOGS_BURNT,
    TEAK_LOGS_BURNT,
    ARCTIC_PINE_LOGS_BURNT,
    MAPLE_LOGS_BURNT,
    MAHOGANY_LOGS_BURNT,
    YEW_LOGS_BURNT,
    MAGIC_LOGS_BURNT,
    REDWOOD_LOGS_BURNT,
    RED_LOGS_BURNT,
    GREEN_LOGS_BURNT,
    BLUE_LOGS_BURNT,
    WHITE_LOGS_BURNT,
    PURPLE_LOGS_BURNT,
    KINDLING_BURNT,

    /**
     * Cooking
     */
    JUGS_OF_WINE_MADE,
    COOKED_FOOD,
    BURNT_FOOD,
    COOKED_ON_FIRE,

    /**
     * Prayer
     */
    FIENDISH_ASHES_BURIED,
    VILE_ASHES_BURIED,
    MALICIOUS_ASHES_BURIED,
    ABYSSAL_ASHES_BURIED,
    INFERNAL_ASHES_BURIED,

    REGULAR_BONES_BURIED,
    BURNT_BONES_BURIED,
    BAT_BONES_BURIED,
    WOLF_BONES_BURIED,
    BIG_BONES_BURIED,
    LONG_BONES_BURIED,
    CURVED_BONES_BURIED,
    JOGRE_BONES_BURIED,
    BABYDRAGON_BONES_BURIED,
    DRAGON_BONES_BURIED,
    ZOGRE_BONES_BURIED,
    OURG_BONES_BURIED,
    MONKEY_BONES_BURIED,
    WYVERN_BONES_BURIED,
    DAGANNOTH_BONES_BURIED,
    LAVA_DRAGON_BONES_BURIED,
    SUPERIOR_DRAGON_BONES_BURIED,
    WYRM_BONES_BURIED,
    DRAKE_BONES_BURIED,
    HYDRA_BONES_BURIED,
    REGULAR_BONES_ALTAR,
    BURNT_BONES_ALTAR,
    BAT_BONES_ALTAR,
    WOLF_BONES_ALTAR,
    BIG_BONES_ALTAR,
    LONG_BONES_ALTAR,
    CURVED_BONES_ALTAR,
    JOGRE_BONES_ALTAR,
    BABYDRAGON_BONES_ALTAR,
    DRAGON_BONES_ALTAR,
    ZOGRE_BONES_ALTAR,
    OURG_BONES_ALTAR,
    MONKEY_BONES_ALTAR,
    WYVERN_BONES_ALTAR,
    DAGANNOTH_BONES_ALTAR,
    LAVA_DRAGON_BONES_ALTAR,
    SUPERIOR_DRAGON_BONES_ALTAR,
    WYRM_BONES_ALTAR,
    DRAKE_BONES_ALTAR,
    HYDRA_BONES_ALTAR,

    /**
     * Farming
     */
    HARVESTED_POTATO,
    HARVESTED_ONION,
    HARVESTED_CABBAGE,
    HARVESTED_TOMATO,
    HARVESTED_SWEETCORN,
    HARVESTED_STRAWBERRY,
    HARVESTED_WATERMELON,
    HARVESTED_SNAPE_GRASS,
    HARVESTED_MARIGOLDS,
    HARVESTED_ROSEMARY,
    HARVESTED_NASTURTIUM,
    HARVESTED_WOAD,
    HARVESTED_LIMPWURT,
    HARVESTED_WHITE_LILY,

    HARVESTED_GUAM,
    HARVESTED_MARRENTILL,
    HARVESTED_TARROMIN,
    HARVESTED_HARRALANDER,
    HARVESTED_RANARR,
    HARVESTED_TOADFLAX,
    HARVESTED_IRIT,
    HARVESTED_AVANTOE,
    HARVESTED_KWUARM,
    HARVESTED_SNAPDRAGON,
    HARVESTED_CADANTINE,
    HARVESTED_LANTADYME,
    HARVESTED_DWARF_WEED,
    HARVESTED_TORSTOL,

    HARVESTED_NIGHTSHADE,
    HARVESTED_BITTERCAP,
    GROWN_APPLE,
    GROWN_BANANA,
    GROWN_ORANGE,
    GROWN_CURRY,
    GROWN_PINEAPPLE,
    GROWN_PAPAYA,
    GROWN_PALM,
    GROWN_DRAGONFRUIT,
    GROWN_OAK,
    GROWN_WILLOW,
    GROWN_MAPLE,
    GROWN_YEW,
    GROWN_MAGIC,
    GROWN_TEAK,
    GROWN_MAHOGANY,
    GROWN_REDBERRY,
    GROWN_CADAVABERRY,
    GROWN_DWELLBERRY,
    GROWN_JANGERBERRY,
    GROWN_WHITEBERRY,
    GROWN_POISON_IVY,
    HARVESTED_BARLEY,
    HARVESTED_HAMMERSTONE,
    HARVESTED_ASGARNIAN,
    HARVESTED_JUTE,
    HARVESTED_YANILLIAN,
    HARVESTED_KRANDORIAN,
    HARVESTED_WILDBLOOD,
    GROWN_CALQUAT,
    GROWN_CACTUS,
    GROWN_POTATO_CACTUS,
    GROWN_SPIRIT_TREE,
    GROWN_CELASTRUS_TREE,
    GROWN_REDWOOD_TREE,
    GROWN_CRYSTAL_TREE,
    GROWN_GRAPE_VINES,
    GROWN_SEAWEED,

    FARMING_CONTRACTS_COMPLETED,

    /**
     * Fishing
     */
    TOTAL_FISH,

    /**
     * Motherlode mine
     */
    MINED_PAYDIRT,
    CLEANED_PAYDIRT,

    /**
     * Wintertodt
     */
    LIFETIME_WINTERTODT_POINTS,
    WINTERTODT_SUBDUED,

    /**
     * Hunter
     */
    CAUGHT_SWIFT,
    CAUGHT_WARBLER,
    CAUGHT_LONGTAIL,
    CAUGHT_TWITCH,
    CAUGHT_WAGTAIL,

    CAUGHT_GREY_CHINCHOMPA,
    CAUGHT_RED_CHINCHOMPA,
    CAUGHT_BLACK_CHINCHOMPA,

    CAUGHT_SWAMP_LIZARD,
    CAUGHT_ORANGE_SALAMANDER,
    CAUGHT_RED_SALAMANDER,
    CAUGHT_BLACK_SALAMANDER,

    CAUGHT_WILD_KEBBIT,
    CAUGHT_BARB_KEBBIT,
    CAUGHT_PRICKLY_KEBBIT,
    CAUGHT_SABRE_KEBBIT,

    /**
     * PVM
     */
    ABYSSAL_CREATURES_KC,

    /**
     * Loyalty chest
     */
    LOYALTY_CHEST_OPENED,

    /**
     * TP Portal
     */
    TELEPORT_PORTAL_USES,

    /**
     * Slayer tasks
     */
    SLAYER_TASKS_COMPLETED,
    WILDERNESS_SLAYER_TASKS_COMPLETED,

    /**
     * Presets
     */
    PRESETS_LOADED,

    /**
     * NightmareZone
     */
    NMZ_REWARD_POINTS,

    /**
     * Daily tasks
     */
    DAILY_TASKS_COMPLETED,

    /**
     * Clues
     */
    BEGINNER_CLUES_COMPLETED,
    EASY_CLUES_COMPLETED,
    MEDIUM_CLUES_COMPLETED,
    HARD_CLUES_COMPLETED,
    ELITE_CLUES_COMPLETED,
    MASTER_CLUES_COMPLETED,

    /**
     * Chests
     */
    BRIMSTONE_CHESTS_OPENED,
    DARK_CHEST_OPENED,

    DEMON_KILLS,

    IMPLINGS_CAUGHT,
    BUTTERFLIES_CAUGHT,

    ;

    public final int increment(Player player, int amount) {
        set(player, get(player) + amount);
        return get(player);
    }

    public final void decrement(Player player, int amount) {
        set(player, get(player) - amount);
    }

    public final void set(Player player, int amount) {
        player.putAttribute(name(), amount);
    }

    public final int get(Player player) {
        return player.getAttributeIntOrZero(name());
    }

}